### ISSUE TITLE
Strings support

### ISSUE THREAD

**Issue by Rechdan** [sarakusha/typed-struct#1]
- **I'm submitting a ...**

  - [ ] bug report
  - [x] feature request
  - [ ] question about the decisions made in the repository
  - [x] question about how to use this project

  Not sure if there is already a way to use strings here, so I checked both boxes so we can talk about it here 🙂

- **Summary**

  Do we have support for using strings? And a array of String?

- **Off-topic**

  Amazing lib you have going on here, the best on I've found so far!

**Comment by sarakusha** [comment]
Adding string support is easy. Update coming soon. But with arrays of strings it is no longer so easy. If you return a regular array, it will be a snapshot of the state. Changes to the buffer will no longer affect the array, just as changes to the array will not affect the buffer. I am trying to use a proxy.

**Comment by sarakusha** [comment]
Since version 1.3.0, strings and string arrays are supported.

* off-topic
It came as a surprise to me that `yarn` publishes all files, regardless of the `package.json/files`. Because of this, the package was too large. `npm` solved this problem.
