### ISSUE TITLE
Not available in ES6 mode

### ISSUE THREAD

**Issue by awake23** [sarakusha/typed-struct#7]
import Struct from 'typed-struct';

const MyStructure = new Struct('MyStructure').Int8('foo').UInt16LE('bar').compile()
console.log(new MyStructure())

error: TypeError: Struct is not a constructor

**Comment by awake23** [comment]
import struct from 'typed-struct';
const Struct = struct.default

Planned support Decorator ?

**Comment by sarakusha** [comment]
the commit 7a7ea4dc8afe83454deab013dd104bbeb6a28253 solved the issue. 
default export replaced with named export
